In [11]:
print("Test ...")

Test ...

In [1]:
# Create the Spark session via Databricks Connect.
# `spark` is auto-injected in the Databricks web UI, but NOT when running
# locally in VSCode — so we build it here. The Databricks VSCode extension
# supplies the cluster/host/auth via environment variables.
from databricks.connect import DatabricksSession

spark = DatabricksSession.builder.getOrCreate()

In [7]:
spark.sql("""
SELECT *
FROM nyctaxi.gold.daily_trips_summary
WHERE pickup_date = '2024-01-02'
""")

DataFrame[pickup_date: date, total_trips: bigint, average_passengers: int, average_distance: double, total_fare: double, max_fare: double, min_fare: double, total_revenue: double]

In [4]:
spark.sql("""
SELECT * FROM nyctaxi.silver.zones LIMIT 5;
""")

DataFrame[location_id: int, borough: string, zone: string, service_zone: string, valid_from: timestamp, valid_to: timestamp]

In [8]:
path = "abfss://population-data@tokeexternalstorage2026.dfs.core.windows.net/country-data/countries_population.snappy.parquet"

df = spark.read.format("parquet").load(path=path)
df.show()

+----------+--------------------+--------------------+------------+----------+--------------------+----------+--------+---------+-------------+
|country_id|                name|         nationality|country_code|iso_alpha2|             capital|population|area_km2|region_id|sub_region_id|
+----------+--------------------+--------------------+------------+----------+--------------------+----------+--------+---------+-------------+
|       210|           Sri Lanka|          Sri Lankan|         LKA|        LK|Sri Jayawardenapu...|  21323733|   65610|       30|           30|
|       211|               Sudan|            Sudanese|         SDN|        SD|            Khartoum|  42813238| 1886068|       50|           40|
|       212|            Suriname|          Surinamese|         SUR|        SR|          Paramaribo|    581372|  163820|       10|           10|
|       213|Svalbard and Jan ...|            Svalbard|         SJM|        SJ|        Longyearbyen|      2667|   61399|       20|          120|
|       214|              Sweden|             Swedish|         SWE|        SE|           Stockholm|  10036379|  450295|       20|          120|
|       215|         Switzerland|               Swiss|         CHE|        CH|                Bern|   8591365|   41284|       20|          150|
|       216|Syrian Arab Republic|              Syrian|         SYR|        SY|            Damascus|  17070135|  185180|       30|          170|
|       217|Taiwan (Province ...|           Taiwanese|         TWN|        TW|              Taipei|  23773876|   36193|       30|           60|
|       218|          Tajikistan|         Tajikistani|         TJK|        TJ|            Dushanbe|   9321018|  143100|       30|          110|
|       219|Tanzania (United ...|           Tanzanian|         TZA|        TZ|              Dodoma|  58005463|  945087|       50|          160|
|       220|            Thailand|                Thai|         THA|        TH|             Bangkok|  69625582|  513120|       30|          100|
|       221|         Timor-Leste|            Timorese|         TLS|        TL|                Dili|   1293119|   14874|       30|          100|
|       222|                Togo|            Togolese|         TGO|        TG|                LomÈ|   8082366|   56785|       50|          160|
|       223|             Tokelau|           Tokelauan|         TKL|        TK|            Nukunonu|      1340|      12|       40|           20|
|       224|               Tonga|              Tongan|         TON|        TO|          Nukuøalofa|    104494|     747|       40|           20|
|       225| Trinidad and Tobago|Trinidadian or To...|         TTO|        TT|       Port of Spain|   1394973|    5130|       10|           10|
|       226|             Tunisia|            Tunisian|         TUN|        TN|               Tunis|  11694719|  163610|       50|           40|
|       227|              Turkey|             Turkish|         TUR|        TR|              Ankara|  83429615|  783562|       30|          170|
|       228|        Turkmenistan|             Turkmen|         TKM|        TM|            Ashgabat|   5942089|  488100|       30|          110|
|       229|Turks and Caicos ...|Turks and Caicos ...|         TCA|        TC|       Cockburn Town|     38191|     948|       10|           10|
+----------+--------------------+--------------------+------------+----------+--------------------+----------+--------+---------+-------------+
only showing top 20 rows

In [3]:
spark.sql("""
DELETE FROM nyctaxi.gold.daily_trips_summary
WHERE pickup_date >= '2025-07-01'
""")

DataFrame[num_affected_rows: bigint]

In [5]:
spark.sql("""
SELECT COUNT(*) FROM nyctaxi.gold.daily_trips_summary
WHERE pickup_date >= '2025-07-01'
""")

DataFrame[COUNT(*): bigint]

In [6]:
spark.sql("DESCRIBE nyctaxi.landing.trips_raw")

DataFrame[col_name: string, data_type: string, comment: string]

In [8]:
%sql
ALTER TABLE nyctaxi.landing.trips_raw ALTER COLUMN VendorID TYPE BIGINT;

AnalysisException: [DELTA_UNSUPPORTED_ALTER_TABLE_CHANGE_COL_OP] ALTER TABLE CHANGE COLUMN is not supported for changing column VendorID from INT to BIGINT.

JVM stacktrace:
com.databricks.sql.transaction.tahoe.DeltaAnalysisException
	at com.databricks.sql.transaction.tahoe.DeltaErrorsBase.alterTableChangeColumnException(DeltaErrors.scala:885)
	at com.databricks.sql.transaction.tahoe.DeltaErrorsBase.alterTableChangeColumnException$(DeltaErrors.scala:878)
	at com.databricks.sql.transaction.tahoe.DeltaErrors$.alterTableChangeColumnException(DeltaErrors.scala:4417)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.verifyColumnChange(alterDeltaTableCommands.scala:1736)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.$anonfun$run$40(alterDeltaTableCommands.scala:1376)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$.transform$1(SchemaUtils.scala:1502)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$.transformSchema(SchemaUtils.scala:1532)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.transformSchemaOnce$1(alterDeltaTableCommands.scala:1373)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.$anonfun$run$46(alterDeltaTableCommands.scala:1448)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.$anonfun$run$38(alterDeltaTableCommands.scala:1448)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.withOperationTypeTag(DeltaLogging.scala:854)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.withOperationTypeTag$(DeltaLogging.scala:841)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.withOperationTypeTag(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperationInternal$2(DeltaLogging.scala:527)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite(DeltaLogging.scala:969)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite$(DeltaLogging.scala:966)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.recordFrameProfileWithCallSite(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperationInternal$1(DeltaLogging.scala:526)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:531)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.spark.util.PublicDBLogging.recordOperationWithResultTags(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:532)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:496)
	at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:104)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:193)
	at com.databricks.spark.util.UsageLogger.recordOperation(UsageLogger.scala:78)
	at com.databricks.spark.util.UsageLogger.recordOperation$(UsageLogger.scala:65)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:152)
	at com.databricks.spark.util.UsageLogging.recordOperation(UsageLogger.scala:537)
	at com.databricks.spark.util.UsageLogging.recordOperation$(UsageLogger.scala:516)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.recordOperation(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperationInternal(DeltaLogging.scala:525)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:515)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:504)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.recordDeltaOperation(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.run(alterDeltaTableCommands.scala:1334)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.$anonfun$alterTable$10(AbstractDeltaCatalog.scala:2903)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.sql.transaction.tahoe.redirect.RedirectFeature$.withUpdateTableRedirectDDL(TableRedirect.scala:810)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.$anonfun$alterTable$1(AbstractDeltaCatalog.scala:2495)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite(DeltaLogging.scala:969)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite$(DeltaLogging.scala:966)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.recordFrameProfileWithCallSite(AbstractDeltaCatalog.scala:199)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.alterTable(AbstractDeltaCatalog.scala:2460)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalogWithIcebergSupport.alterTable(DeltaCatalogWithIcebergSupport.scala:202)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog.alterTable(AbstractDeltaCatalog.scala:181)
	at com.databricks.sql.managedcatalog.UnityCatalogV2Proxy.alterTable(UnityCatalogV2Proxy.scala:308)
	at com.databricks.sql.managedcatalog.UnityCatalogV2Proxy.alterTable(UnityCatalogV2Proxy.scala:58)
	at org.apache.spark.sql.execution.datasources.v2.AlterTableExec.run(AlterTableExec.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.$anonfun$result$2(V2CommandExec.scala:48)
	at org.apache.spark.sql.execution.SparkPlan.runCommandInAetherOrSpark(SparkPlan.scala:202)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.$anonfun$result$1(V2CommandExec.scala:48)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:47)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:45)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:56)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$12(QueryExecution.scala:1932)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$11(QueryExecution.scala:1926)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution$.executeWithCaches$1(QueryExecution.scala:1926)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$10(QueryExecution.scala:1932)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:266)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$9(QueryExecution.scala:1919)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$23(SQLExecution.scala:1024)
	at com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$21(SQLExecution.scala:945)
	at com.databricks.unity.UCSManager$.withTemporaryScope(UCSManager.scala:168)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$20(SQLExecution.scala:847)
	at org.apache.spark.sql.execution.SQLExecution$.withSessionTagsApplied(SQLExecution.scala:1476)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$19(SQLExecution.scala:836)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$18(SQLExecution.scala:836)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:1511)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$1(SQLExecution.scala:835)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId0(SQLExecution.scala:577)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:1429)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$8(QueryExecution.scala:1919)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1784)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$7(QueryExecution.scala:1915)
	at org.apache.spark.sql.execution.QueryExecution.withMVTagsIfNecessary(QueryExecution.scala:690)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$4(QueryExecution.scala:1900)
	at scala.Option.map(Option.scala:242)
	at org.apache.spark.sql.execution.QueryExecution$.executeWithMVTags$1(QueryExecution.scala:1900)
	at org.apache.spark.sql.execution.QueryExecution$.runCommand(QueryExecution.scala:1913)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$eagerlyExecute$1(QueryExecution.scala:727)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:744)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:736)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:595)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:142)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:595)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:48)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:361)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:357)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:48)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:48)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:571)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:736)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:736)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyCommandExecuted$1(QueryExecution.scala:646)
	at scala.util.Try$.apply(Try.scala:217)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1770)
	at org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1820)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:651)
	at org.apache.spark.sql.classic.Dataset.<init>(Dataset.scala:437)
	at org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$3(Dataset.scala:158)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.classic.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1330)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.classic.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1330)
	at org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:149)
	at org.apache.spark.sql.classic.SparkSession.$anonfun$sql$6(SparkSession.scala:1015)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.classic.SparkSession.sql(SparkSession.scala:980)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:4264)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:4057)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3756)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:517)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:405)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:745)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:745)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:744)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$execute$1(ExecuteThreadRunner.scala:196)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries(UtilizationMetrics.scala:72)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries$(UtilizationMetrics.scala:69)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.recordActiveQueries(ExecuteThreadRunner.scala:57)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:188)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$3(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.DBRTracing$.withSpanFromParent(DBRTracing.scala:70)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:128)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:133)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:132)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:721)

In [16]:
spark.sql("""
ALTER TABLE nyctaxi.landing.trips_raw
SET TBLPROPERTIES ('delta.enableTypeWidening' = 'true');""")

DataFrame[]

In [13]:
spark.sql("""
ALTER TABLE nyctaxi.landing.trips_raw ALTER COLUMN VendorID TYPE BIGINT;""")

DataFrame[]

In [14]:
spark.sql("DESCRIBE nyctaxi.landing.trips_raw")

DataFrame[col_name: string, data_type: string, comment: string]

In [18]:
spark.sql("""ALTER TABLE nyctaxi.landing.trips_raw ALTER COLUMN passenger_count TYPE DOUBLE;""")

AnalysisException: [DELTA_UNSUPPORTED_ALTER_TABLE_CHANGE_COL_OP] ALTER TABLE CHANGE COLUMN is not supported for changing column passenger_count from BIGINT to DOUBLE.

JVM stacktrace:
com.databricks.sql.transaction.tahoe.DeltaAnalysisException
	at com.databricks.sql.transaction.tahoe.DeltaErrorsBase.alterTableChangeColumnException(DeltaErrors.scala:885)
	at com.databricks.sql.transaction.tahoe.DeltaErrorsBase.alterTableChangeColumnException$(DeltaErrors.scala:878)
	at com.databricks.sql.transaction.tahoe.DeltaErrors$.alterTableChangeColumnException(DeltaErrors.scala:4417)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.verifyColumnChange(alterDeltaTableCommands.scala:1736)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.$anonfun$run$40(alterDeltaTableCommands.scala:1376)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$.transform$1(SchemaUtils.scala:1502)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$.transformSchema(SchemaUtils.scala:1532)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.transformSchemaOnce$1(alterDeltaTableCommands.scala:1373)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.$anonfun$run$46(alterDeltaTableCommands.scala:1448)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.$anonfun$run$38(alterDeltaTableCommands.scala:1448)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.withOperationTypeTag(DeltaLogging.scala:854)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.withOperationTypeTag$(DeltaLogging.scala:841)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.withOperationTypeTag(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperationInternal$2(DeltaLogging.scala:527)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite(DeltaLogging.scala:969)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite$(DeltaLogging.scala:966)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.recordFrameProfileWithCallSite(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperationInternal$1(DeltaLogging.scala:526)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:531)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.spark.util.PublicDBLogging.recordOperationWithResultTags(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:532)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:496)
	at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:29)
	at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:104)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:193)
	at com.databricks.spark.util.UsageLogger.recordOperation(UsageLogger.scala:78)
	at com.databricks.spark.util.UsageLogger.recordOperation$(UsageLogger.scala:65)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:152)
	at com.databricks.spark.util.UsageLogging.recordOperation(UsageLogger.scala:537)
	at com.databricks.spark.util.UsageLogging.recordOperation$(UsageLogger.scala:516)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.recordOperation(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperationInternal(DeltaLogging.scala:525)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:515)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:504)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.recordDeltaOperation(alterDeltaTableCommands.scala:1327)
	at com.databricks.sql.transaction.tahoe.commands.AlterTableChangeColumnDeltaCommand.run(alterDeltaTableCommands.scala:1334)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.$anonfun$alterTable$10(AbstractDeltaCatalog.scala:2903)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.sql.transaction.tahoe.redirect.RedirectFeature$.withUpdateTableRedirectDDL(TableRedirect.scala:810)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.$anonfun$alterTable$1(AbstractDeltaCatalog.scala:2495)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite(DeltaLogging.scala:969)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfileWithCallSite$(DeltaLogging.scala:966)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.recordFrameProfileWithCallSite(AbstractDeltaCatalog.scala:199)
	at com.databricks.sql.transaction.tahoe.catalog.AbstractDeltaCatalog.alterTable(AbstractDeltaCatalog.scala:2460)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalogWithIcebergSupport.alterTable(DeltaCatalogWithIcebergSupport.scala:202)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog.alterTable(AbstractDeltaCatalog.scala:181)
	at com.databricks.sql.managedcatalog.UnityCatalogV2Proxy.alterTable(UnityCatalogV2Proxy.scala:308)
	at com.databricks.sql.managedcatalog.UnityCatalogV2Proxy.alterTable(UnityCatalogV2Proxy.scala:58)
	at org.apache.spark.sql.execution.datasources.v2.AlterTableExec.run(AlterTableExec.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.$anonfun$result$2(V2CommandExec.scala:48)
	at org.apache.spark.sql.execution.SparkPlan.runCommandInAetherOrSpark(SparkPlan.scala:202)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.$anonfun$result$1(V2CommandExec.scala:48)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:47)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:45)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:56)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$12(QueryExecution.scala:1932)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$11(QueryExecution.scala:1926)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution$.executeWithCaches$1(QueryExecution.scala:1926)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$10(QueryExecution.scala:1932)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:266)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$9(QueryExecution.scala:1919)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$23(SQLExecution.scala:1024)
	at com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$21(SQLExecution.scala:945)
	at com.databricks.unity.UCSManager$.withTemporaryScope(UCSManager.scala:168)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$20(SQLExecution.scala:847)
	at org.apache.spark.sql.execution.SQLExecution$.withSessionTagsApplied(SQLExecution.scala:1476)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$19(SQLExecution.scala:836)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$18(SQLExecution.scala:836)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:1511)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$1(SQLExecution.scala:835)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId0(SQLExecution.scala:577)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:1429)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$8(QueryExecution.scala:1919)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1784)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$7(QueryExecution.scala:1915)
	at org.apache.spark.sql.execution.QueryExecution.withMVTagsIfNecessary(QueryExecution.scala:690)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$runCommand$4(QueryExecution.scala:1900)
	at scala.Option.map(Option.scala:242)
	at org.apache.spark.sql.execution.QueryExecution$.executeWithMVTags$1(QueryExecution.scala:1900)
	at org.apache.spark.sql.execution.QueryExecution$.runCommand(QueryExecution.scala:1913)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$eagerlyExecute$1(QueryExecution.scala:727)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:744)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:736)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:595)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:142)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:595)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:48)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:361)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:357)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:48)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:48)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:571)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:736)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:736)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyCommandExecuted$1(QueryExecution.scala:646)
	at scala.util.Try$.apply(Try.scala:217)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1770)
	at org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1820)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:651)
	at org.apache.spark.sql.classic.Dataset.<init>(Dataset.scala:437)
	at org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$3(Dataset.scala:158)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.classic.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1330)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.classic.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1330)
	at org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:149)
	at org.apache.spark.sql.classic.SparkSession.$anonfun$sql$6(SparkSession.scala:1015)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.classic.SparkSession.sql(SparkSession.scala:980)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:4264)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:4057)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3756)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:517)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:405)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:745)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:745)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:744)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$execute$1(ExecuteThreadRunner.scala:196)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries(UtilizationMetrics.scala:72)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries$(UtilizationMetrics.scala:69)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.recordActiveQueries(ExecuteThreadRunner.scala:57)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:188)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$3(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.DBRTracing$.withSpanFromParent(DBRTracing.scala:70)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:128)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:133)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:132)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:721)

In [68]:
%sql
CREATE OR REPLACE TABLE nyctaxi.landing.trips_raw (
    VendorID BIGINT,
    tpep_pickup_datetime TIMESTAMP_NTZ,
    tpep_dropoff_datetime TIMESTAMP_NTZ,
    passenger_count DOUBLE,
    trip_distance DOUBLE,
    RatecodeID DOUBLE,
    store_and_fwd_flag STRING,
    PULocationID BIGINT,
    DOLocationID BIGINT,
    payment_type LONG,
    fare_amount DOUBLE,
    extra DOUBLE,
    mta_tax DOUBLE,
    tip_amount DOUBLE,
    tolls_amount DOUBLE,
    improvement_surcharge DOUBLE,
    total_amount DOUBLE,
    congestion_surcharge DOUBLE,
    airport_fee DOUBLE,
    cbd_congestion_fee DOUBLE
);

DataFrame[]

In [67]:
%sql
CREATE OR REPLACE TABLE nyctaxi.bronze.trips (
    vendor_id INT,
    pickup_datetime TIMESTAMP,
    dropoff_datetime TIMESTAMP,
    passenger_count INT,
    trip_distance DOUBLE,
    rate_code_id INT,
    store_and_fwd_flag STRING,
    pickup_location_id INT,
    dropoff_location_id INT,
    payment_type LONG,
    fare_amount DOUBLE,
    extra DOUBLE,
    mta_tax DOUBLE,
    tip_amount DOUBLE,
    tolls_amount DOUBLE,
    improvement_surcharge DOUBLE,
    total_amount DOUBLE,
    congestion_surcharge DOUBLE,
    airport_fee DOUBLE,
    cbd_congestion_fee DOUBLE,
    processed_timestamp TIMESTAMP
);

DataFrame[]

In [64]:
%sql
DESCRIBE nyctaxi.landing.trips_raw;

DataFrame[col_name: string, data_type: string, comment: string]

In [69]:
%sql
DESCRIBE nyctaxi.bronze.trips;

DataFrame[col_name: string, data_type: string, comment: string]

In [66]:
%sql
DESCRIBE nyctaxi.silver.trips;

DataFrame[col_name: string, data_type: string, comment: string]

In [63]:

for m in range(12):
    month = f"2023-{(m + 1):02d}"
    df = spark.read.parquet(f"/Volumes/nyctaxi/landing/data_sources/nyctaxi_yellow/trips/{month}/yellow_tripdata_{month}.parquet")
    schema = list(df.schema.fields)
    print(f"PULocationID: {schema[7].dataType} RatecodeID: {schema[5].dataType}")

PULocationID: LongType() RatecodeID: DoubleType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()
PULocationID: IntegerType() RatecodeID: LongType()

In [54]:
df.schema.fields[7].dataType

StructField('PULocationID', IntegerType(), True)

In [28]:
df

DataFrame[VendorID: int, tpep_pickup_datetime: timestamp_ntz, tpep_dropoff_datetime: timestamp_ntz, passenger_count: bigint, trip_distance: double, RatecodeID: bigint, store_and_fwd_flag: string, PULocationID: int, DOLocationID: int, payment_type: bigint, fare_amount: double, extra: double, mta_tax: double, tip_amount: double, tolls_amount: double, improvement_surcharge: double, total_amount: double, congestion_surcharge: double, Airport_fee: double, cbd_congestion_fee: double]

In [29]:
df.filter("PULocationID IS NULL")

DataFrame[VendorID: int, tpep_pickup_datetime: timestamp_ntz, tpep_dropoff_datetime: timestamp_ntz, passenger_count: bigint, trip_distance: double, RatecodeID: bigint, store_and_fwd_flag: string, PULocationID: int, DOLocationID: int, payment_type: bigint, fare_amount: double, extra: double, mta_tax: double, tip_amount: double, tolls_amount: double, improvement_surcharge: double, total_amount: double, congestion_surcharge: double, Airport_fee: double, cbd_congestion_fee: double]

In [30]:
display(df.schema)

StructType([StructField('VendorID', IntegerType(), True), StructField('tpep_pickup_datetime', TimestampNTZType(), True), StructField('tpep_dropoff_datetime', TimestampNTZType(), True), StructField('passenger_count', LongType(), True), StructField('trip_distance', DoubleType(), True), StructField('RatecodeID', LongType(), True), StructField('store_and_fwd_flag', StringType(), True), StructField('PULocationID', IntegerType(), True), StructField('DOLocationID', IntegerType(), True), StructField('payment_type', LongType(), True), StructField('fare_amount', DoubleType(), True), StructField('extra', DoubleType(), True), StructField('mta_tax', DoubleType(), True), StructField('tip_amount', DoubleType(), True), StructField('tolls_amount', DoubleType(), True), StructField('improvement_surcharge', DoubleType(), True), StructField('total_amount', DoubleType(), True), StructField('congestion_surcharge', DoubleType(), True), StructField('Airport_fee', DoubleType(), True), StructField('cbd_congestion_fee', DoubleType(), True)])